apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics

resources:
  - namespace.yaml
  - collector/deployment.yaml
  - collector/hpa.yaml
  - processor/keda-scaledobject.yaml
