global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: collector
    static_configs:
      - targets: ['collector:3000']
    metrics_path: /metrics

  - job_name: processor
    static_configs:
      - targets: ['processor:9091']
    metrics_path: /metrics

  - job_name: query-api
    static_configs:
      - targets: ['query-api:3002']
    metrics_path: /metrics

  - job_name: redpanda
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: /metrics
